version: "2.2"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      node.name: es01
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.security.enabled: false
      discovery.type: single-node
      xpack.license.self_generated.type: ${LICENSE}
      http.cors.enabled: true
      http.cors.allow-origin: "\"*\""
      http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization
    networks:
      - uc-mvc-net
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://127.0.0.1:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:${SQL_EDGE_VERSION}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_EDGE_SA_PASSWORD}
    ports:
      - ${SQL_EDGE_PORT}:1433
    networks:
      - uc-mvc-net
volumes:
  data01:
    driver: local
  kibanadata:
    driver: local

networks:
  uc-mvc-net:
    driver: bridge
