version: "2.2"

services:
  elasticvue:
    image: cars10/elasticvue
    ports:
      - 9210:18464
    networks:
      - es-net
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=${LICENSE}
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:9210
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    networks:
      - es-net
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://127.0.0.1:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      - es01
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - data01:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=${LICENSE}
      - ELASTICSEARCH_URL=http://es01:${ES_PORT}
      - ELASTICSEARCH_HOSTS=http://es01:${ES_PORT}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - es-net
    ports:
      - ${KIBANA_PORT}:5601
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes: 
  data01:
    driver: local
  kibanadata:
    driver: local
    
networks:
  es-net:
    driver: bridge
